<?php
/**
 * Created by PhpStorm.
 * User: 18710
 * Date: 2017/7/10
 * Time: 15:12
 */

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model{

    // 指定表名
    protected $table = 'student';

    // 指定id
    protected $primaryKey = 'id';

    // 指定可以新增的字段，可以批量赋值的字段
    protected $fillable = ['name', 'age', 'sex'];

    // 指定不可以新增的字段
    protected $guarded = [];

    // 自动维护时间戳
    public $timestamps = true;

    // 设置时间
    protected function getDateFormat()
    {
//        return parent::getDateFormat(); // TODO: Change the autogenerated stub
        return time();
    }

    // 不自动格式化时间格式
    protected function asDateTime($value)
    {
//        return parent::asDateTime($value); // TODO: Change the autogenerated stub
        return $value;
    }

}